<?php

namespace frontend\modules\registrationandlogin\models;

use Yii;

/**
 * This is the model class for table "registration".
 *
 * @property int $id
 * @property string $username
 * @property string $email
 * @property string $password
 */
class Registration extends \yii\db\ActiveRecord
{
    public static function getDb()
    {
        return Yii::$app->db;// TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%registration}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['username', 'email', 'password'], 'required'],
            [['username', 'email', 'password'], 'string', 'max' => 50],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'email' => 'Email',
            'password' => 'Password',
        ];
    }
}
