<?php
/**
 * Created by PhpStorm.
 * User: cedcoss
 * Date: 2/8/18
 * Time: 4:55 PM
 */
namespace frontend\models;

use Yii;
use yii\db\ActiveRecord;

class DbNew extends ActiveRecord{


    public static function getDb()
    {
        return Yii::$app->db2; // TODO: Change the autogenerated stub
    }
    public static function tableName()
    {
        return '{{%user}}';
    }
    public function rules()
    {
        return [
            ['username', 'trim'],
            ['username', 'required'],
            ['username', 'unique', 'message' => 'This username has already been taken.'],
            ['username', 'string', 'min' => 2, 'max' => 255],

            ['email', 'trim'],
            ['email', 'required'],
            ['email', 'email'],
            ['email', 'string', 'max' => 255],
            ['email', 'unique', 'message' => 'This email address has already been taken.'],

            ['phone','number'],
            ['phone','required'],
            ['phone','string','min'=>10,'max'=>10],


            ['image','file','skipOnEmpty' => true, 'extensions' => 'png, jpg ,jpeg', 'message'=>'{extensions} files only', 'on'=>'update'],
            /*  ['image','image'],*/


            ['password', 'required'],
            ['password', 'string','min'=>8],
            ['password', 'match','pattern' => '/^((?=.*\d)(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$/', 'message'=>'Password must contain atleast 1 capital letter, 1 number and 1 special character.'],


            ['dob','required'],
            ['dob','string'],
            //['username,dob,image,password,email,phone', 'safe']



        ];
    }


}