<?php
/**
 * Created by PhpStorm.
 * User: cedcoss
 * Date: 8/8/18
 * Time: 10:43 AM
 */

namespace frontend\modules\display;

use yii\base\Module;

class Display extends Module{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

}